runtime: python39
instance_class: F4

automatic_scaling:
  min_idle_instances: 0 
  max_idle_instances: 1  
  min_instances: 0  
  max_instances: 3 
  target_cpu_utilization: 0.8  
  target_throughput_utilization: 0.75

env_variables:
  PORT: '8080'

handlers:
- url: /.*
  script: auto
